version: '3.6'

services:
  web:
    build: .
     
    volumes:
      - .:/home/app/webapp
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      BASE_URL: ${BASE_URL}
      APP_DB_HOST: db 
      DATABASE_URL: postgres://postgres@db
  db:
    image: postgres:10.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./postgresdb:/postgresdb

volumes:
  postgres_data:
