FROM ruby:2.7
RUN apt-get update -qq \
        && apt-get install -y nodejs postgresql-client \
        && apt-get install -y build-essential patch ruby-dev \
        # && zlib1j-dev liblzma \
        && apt-get install libpq-dev

RUN gem install nokogiri -v '1.10.10' --source 'https://rubygems.org/'
RUN apt-get install -y rails

RUN mkdir /spacefinder
WORKDIR /spacefinder
ADD Gemfile Gemfile.lock /spacefinder/
RUN bundle install

# Add a script to be executed every time the container starts.
COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]
EXPOSE 3000

# Start the main process.
CMD ["rails", "server", "-b", "0.0.0.0"]