# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

<%
if Rails.env.production?
  secret_key = Spacefinder.get_file_envar('SPACEFINDER_SECRET_KEY', nil) or \
               Spacefinder.get_file_envar('SECRET_KEY_BASE')
else
  secret_key = 'non-production-placeholder'
end
%>

development:
  secret_key_base: <%= secret_key %>

test:
  secret_key_base: <%= secret_key %>

production:
  secret_key_base: <%= secret_key %>
