name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0"
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - run: bundle exec rake db:create test
        env:
          SPACEFINDER_DATABASE_HOST: localhost
          SPACEFINDER_DATABASE_PASSWORD: spacefinder
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: spacefinder_development
          POSTGRES_USER: spacefinder
          POSTGRES_PASSWORD: spacefinder
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
  test_docker_image:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: docker compose -f docker/docker-compose.yml build
      - name: Run app and verify /health_check is successful
        run: |
          sudo docker compose \
            -f docker/docker-compose.yml -f docker/docker-compose.test.yml \
            up --abort-on-container-exit
